#!/bin/sh

cat "$1" | grep -E -v '(^[ \t]*#)|(^[ \t]*$)' | while read a b
do
	FILE='nonexistent'

	for dir in /sys/power /sys/devices/system/cpu/cpu0/cpufreq /sys/devices/system/cpu/cpu0/cpufreq/ondemand
	do
		if [ -f $dir/$a ]
		then
			FILE=$dir/$a
			break
		fi
	done

	if [ -w $FILE ]
	then
		echo $b > $FILE
	else
		echo "Don't understand '$a $b'"
	fi
done

