#!/bin/sh

cat "$1" | grep -E -v '(^#)|(^[ \t]*$)' | while read a b
do
    case $a in

	enable_off_mode)  	echo $b > /sys/power/enable_off_mode		;;
	sleep_while_idle)	echo $b > /sys/power/sleep_while_idle		;;
	clocks_off_while_idle)	echo $b > /sys/power/clocks_off_while_idle	;;
	voltage_off_while_idle) echo $b > /sys/power/voltage_off_while_idle	;;
	vdd1_opps_vsel)		echo $b > /sys/power/vdd1_opps_vsel		;;
	dsp_opps_rate)		echo $b > /sys/power/dsp_opps_rate		;;
	sr_vdd1_autocomp)	echo $b > /sys/power/sr_vdd1_autocomp		;;
	sr_vdd2_autocomp)	echo $b > /sys/power/sr_vdd2_autocomp		;;
	smartreflex_vdd1)	echo $b > /sys/power/sr_vdd1_autocomp		;;
	smartreflex_vdd2)	echo $b > /sys/power/sr_vdd2_autocomp		;;

	scaling_governor)	echo $b > /sys/devices/system/cpu/cpu0/cpufreq/scaling_governor 	;;
	scaling_max_freq)	echo $b > /sys/devices/system/cpu/cpu0/cpufreq/scaling_max_freq		;;
	scaling_min_freq)	echo $b > /sys/devices/system/cpu/cpu0/cpufreq/scaling_min_freq		;;
	up_threshold)		echo $b > /sys/devices/system/cpu/cpu0/cpufreq/ondemand/up_threshold	;;
	sampling_rate)		echo $b > /sys/devices/system/cpu/cpu0/cpufreq/ondemand/sampling_rate	;;
	avoid_frequencies)	echo $b > /sys/devices/system/cpu/cpu0/cpufreq/ondemand/avoid_frequencies ;;

	*)			echo "Don't understand '$a $b'"			;;

    esac

done

